
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: dimCliente
    description: "Dimension cliente"
    columns:
      - name: keyCliente
      - name: Cliente
      - name: Genero
      - name: Distrito
      - name: Provincia
      - name: Departamento
      - name: IdCliente
